version: "3.9"
services:
  redis:
    image: "redislabs/redisearch:latest"
    container_name: "redis-tuna"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 10
  api:
    build: "./server/"
    container_name: "tuna-api"
    ports:
      - "5050:5000"
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
